name: Deploy

permissions:
  id-token: write
  contents: read

concurrency:
  group: prod
  cancel-in-progress: true

on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Install packages
        run: npm install -g serverless

      - name: Install serverless-wsgi
        run: serverless plugin install -n serverless-wsgi

      - name: Install serverless-python-requirements
        run: serverless plugin install -n serverless-python-requirements

      - name: Install serverless-plugin-common-excludes
        run: serverless plugin install -n serverless-plugin-common-excludes

      - name: Install serverless-plugin-include-dependencies
        run: serverless plugin install -n serverless-plugin-include-dependencies

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::001057775987:role/GithubActionsOIDC-vxx-Role-ZYPHWRSFIP80
          role-duration-seconds: 900
          aws-region: us-east-1

      - name: Deploy
        run: serverless deploy --verbose
        env:
          VXX_LINK_CACHE: ${{ secrets.VXX_LINK_CACHE }}
          VXX_DATABASE: ${{ secrets.VXX_DATABASE }}
          VXX_METHOD: ${{ secrets.VXX_METHOD }}
          VXX_COLOR: ${{ secrets.VXX_COLOR }}
          VXX_APP_NAME: ${{ secrets.VXX_APP_NAME }}
          VXX_REPO: ${{ secrets.VXX_REPO }}
          VXX_URL: ${{ secrets.VXX_URL }}
          VXX_COMBINATION_METHOD: ${{ secrets.VXX_COMBINATION_METHOD }}
          VXX_GIF_CONVERT_API: ${{ secrets.VXX_GIF_CONVERT_API }}
          VXX_WORKAROUND_TOKENS: ${{ secrets.VXX_WORKAROUND_TOKENS }}
          VXX_PROXIES: ${{ secrets.VXX_PROXIES }}
